// <auto-generated />
using System;
using Crop_Deal.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Crop_Deal.Migrations
{
    [DbContext(typeof(CropDetailDbContext))]
    [Migration("20240122061541_SixthMigrationForCropDetails")]
    partial class SixthMigrationForCropDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Crop_Deal.Model.CropType", b =>
                {
                    b.Property<int>("CropTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CropTypeId"));

                    b.Property<string>("CropTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CropTypeId");

                    b.ToTable("CropTypes");
                });

            modelBuilder.Entity("Crop_Deal.Model.Domain.BankDetails", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IfscCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AccountId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("BankDetails");
                });

            modelBuilder.Entity("Crop_Deal.Model.Domain.CropDetails", b =>
                {
                    b.Property<int>("CropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CropId"));

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CropTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerKg")
                        .HasColumnType("float");

                    b.Property<double>("QuantityInKg")
                        .HasColumnType("float");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CropId");

                    b.HasIndex("CropTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("CropDetails");
                });

            modelBuilder.Entity("Crop_Deal.Model.Domain.Receipt", b =>
                {
                    b.Property<int>("ReciptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReciptId"));

                    b.Property<int>("CropId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DealDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealerId")
                        .HasColumnType("int");

                    b.Property<int>("FarmerId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityRequired")
                        .HasColumnType("int");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int");

                    b.HasKey("ReciptId");

                    b.HasIndex("CropId");

                    b.HasIndex("DealerId");

                    b.HasIndex("FarmerId");

                    b.ToTable("Receipt");
                });

            modelBuilder.Entity("Crop_Deal.Model.Domain.Subscribe", b =>
                {
                    b.Property<int>("SubscribeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscribeId"));

                    b.Property<int>("CropTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("Subscriber")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SubscribeId");

                    b.HasIndex("CropTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Subscribes");
                });

            modelBuilder.Entity("Crop_Deal.Model.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Phone")
                        .HasColumnType("float");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Crop_Deal.Model.Domain.BankDetails", b =>
                {
                    b.HasOne("Crop_Deal.Model.Domain.User", "Users")
                        .WithOne("BankDetails")
                        .HasForeignKey("Crop_Deal.Model.Domain.BankDetails", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Crop_Deal.Model.Domain.CropDetails", b =>
                {
                    b.HasOne("Crop_Deal.Model.CropType", "CropType")
                        .WithMany("CropDetail")
                        .HasForeignKey("CropTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Crop_Deal.Model.Domain.User", "User")
                        .WithMany("CropDetails")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Crop_Deal.Model.Domain.Receipt", b =>
                {
                    b.HasOne("Crop_Deal.Model.Domain.CropDetails", "CropDetails")
                        .WithMany("Receipt")
                        .HasForeignKey("CropId")
                        .IsRequired();

                    b.HasOne("Crop_Deal.Model.Domain.User", "DealerUser")
                        .WithMany("DealerName")
                        .HasForeignKey("DealerId")
                        .IsRequired();

                    b.HasOne("Crop_Deal.Model.Domain.User", "FarmerUser")
                        .WithMany("FarmerName")
                        .HasForeignKey("FarmerId")
                        .IsRequired();

                    b.Navigation("CropDetails");

                    b.Navigation("DealerUser");

                    b.Navigation("FarmerUser");
                });

            modelBuilder.Entity("Crop_Deal.Model.Domain.Subscribe", b =>
                {
                    b.HasOne("Crop_Deal.Model.CropType", "CropTypes")
                        .WithMany("Subscribes")
                        .HasForeignKey("CropTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Crop_Deal.Model.Domain.User", "User")
                        .WithMany("Subscribes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CropTypes");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Crop_Deal.Model.CropType", b =>
                {
                    b.Navigation("CropDetail");

                    b.Navigation("Subscribes");
                });

            modelBuilder.Entity("Crop_Deal.Model.Domain.CropDetails", b =>
                {
                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("Crop_Deal.Model.Domain.User", b =>
                {
                    b.Navigation("BankDetails")
                        .IsRequired();

                    b.Navigation("CropDetails");

                    b.Navigation("DealerName");

                    b.Navigation("FarmerName");

                    b.Navigation("Subscribes");
                });
#pragma warning restore 612, 618
        }
    }
}
